FROM python:3.12-slim AS aw
ARG UID
ARG AW_VERSION=0.0
ARG AW_USER=aw

COPY --chmod=0644 requirements.txt /etc/requirements.txt
COPY --chmod=0644 requirements_test_backend.txt /etc/requirements_test_backend.txt

RUN apt-get update && \
    apt-get -y --no-install-recommends install git git-lfs openssh-client sshpass xmlsec1 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    mkdir -p /data/log && \
    useradd --uid ${UID} --user-group --shell /usr/sbin/nologin --home-dir /home/ansible-webui --create-home ${AW_USER} && \
    chown ${AW_USER}:${AW_USER} /data/log && \
    python3 -m pip install -r /etc/requirements.txt && \
    python3 -m pip install -r /etc/requirements_test_backend.txt

ENV AW_VERSION=${AW_VERSION}.dev \
    AW_DEV=1 \
    AW_ENV='dev' \
    AW_DOCKER=1 \
    AW_SECRET='asdfThisIsSuperSecret!12345678' \
    AW_DB=/repo/src/oxl_ansible_webui/aw.dev.db \
    AW_PATH_PLAY=/repo/test \
    AW_PATH_LOG=/data/log \
    DJANGO_SUPERUSER_USERNAME='ansible' \
    DJANGO_SUPERUSER_PASSWORD='automateMe' \
    DJANGO_SUPERUSER_EMAIL='ansible@localhost' \
    DEV_CLEAN=0 \
    DEV_INIT=1 \
    PYTHONUNBUFFERED=1 \
    PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/ansible-webui/.local/bin
WORKDIR /repo/test
EXPOSE 8000

COPY --chmod=0755 docker/entrypoint_dev_backend.sh /entrypoint.sh
COPY --chmod=0755 docker/entrypoint_dev_unit_tests.sh /entrypoint_unit_tests.sh

USER ${AW_USER}
ENTRYPOINT ["/entrypoint.sh"]
